package com.dicoding.asclepius.utils

const val NUM_THREADS = 4

const val IMAGE_ARGUMENT = "IMAGE_URI_EXTRA"
const val FIRST_ANALYZE_LABEL_RESULT = "FIRST_ANALYZE_LABEL_RESULT"
const val SECOND_ANALYZE_LABEL_RESULT = "SECOND_ANALYZE_LABEL_RESULT"
const val FIRST_SCORE_RESULT = "FIRST_SCORE_RESULT"
const val SECOND_SCORE_RESULT = "SECOND_SCORE_RESULT"